name:                aof2019
version:             0.1.0.0
github:              "jborkowski/aof2019"
license:             BSD3
author:              "Jonatan Borkowski"
maintainer:          "jonatanborkowski@wp.pl"
copyright:           "2019 Jonatan Borkowski"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jborkowski/aof2019#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.5.6.3

library:
  source-dirs: src

executables:
  aof2019-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aof2019

tests:
  aof2019-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aof2019
